name: 'Merge Dogfood Branches'
author: 'Engineering Experience Squad <platform.eng-xp@sonarsource.com>'
description: 'Automatically merges branches prefixed with name "dogfood/" into the dogfood branch'
inputs:
  dogfood-branch:
    description: 'The name of the dogfood branch'
    required: true
    default: 'dogfood-automerge'
outputs:
  dogfood-branch:
    description: 'The name of the dogfood branch'
  sha1:
    description: 'The HEAD sha1 of the dogfood branch'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.dogfood-branch }}
branding:
  icon: 'git-merge'
